# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9dffb3dbe6d5cb1fddf10a0ca1dd9d79b5b414b4b93ad970a987784f98a4af62f4c0ef77ffd7f71e2ef3adfb077e7f423d34be6c7d4f62695a615571d8829cc

test:
  secret_key_base: 0a08ce41bdafb7afb0073ec04dd19687901d2047ea4664e991a3ac55b9e975a0584a629222cb51b6df26390f6dfac3d3dc0906c048672b6c6b35e6322d94b31f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
